version: "3.8"

services:
  localstack-snowflake:
    container_name: "localstack-snowflake"
    image: localstack/snowflake:latest
    networks:
      - localstack
    ports:
      - "4567:4567"
      - "443:443"
    environment:
      - DEBUG=true # set to "true" to enable debug logging
      - GATEWAY_LISTEN=0.0.0.0:4567
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - SF_HOSTNAME_REGEX=localstack-snowflake.*
    healthcheck:
      test: ["CMD-SHELL", "awslocal s3api list-buckets"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "./volume/snowflake:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  localstack-aws:
    container_name: "localstack-aws"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./volume/aws:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack

networks:
  localstack:
    external: false
    driver: bridge
    name: localstack
